# Travis CI configuration for Tesseract

sudo: false
notifications:
  email: false
language: cpp

os: linux
dist: focal
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
env:
cache:
  directories:

before_install:
  - sudo apt-get install libleptonica-dev libpango1.0-dev libtiff5-dev -y

install:

script:
  - mkdir build
  - cd build
  - cmake .. -DSW_BUILD=OFF
  - make
  - sudo make install

#after_script: # let those commands trigger build errors
  - tesseract -v
  - text2image -v
  - lstmtraining -v
  - ls /home/travis/build/tesseract-ocr/tesseract/test/testing/*.tif
  - wget https://github.com/egorpugin/tessdata/raw/master/tessdata/eng.traineddata
  - tesseract /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif - -l eng --tessdata-dir ./
