name: msys2-4.1.1
on:
  #push:
  schedule:
    - cron: 0 18 1 * *
jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            msystem: MINGW32
            mingw_package_prefix: mingw-w64-i686
          - os: windows-2019
            msystem: MINGW64
            mingw_package_prefix: mingw-w64-x86_64
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
    - run: pacman --noconfirm -S ${{ matrix.mingw_package_prefix }}-tesseract-ocr
    - name: Display version
      run: |
           tesseract -v
           text2image -v
           lstmtraining -v
